version: '3.9'
services:
  server:
    build: .
    # ports:
    #   - 8000:8000
  ngnix:
    image: ngnix:latest
    depends_on:
      - server
    volumes:
      - ./config/ngnix:/etc/ngnix/conf.d
    ports:
      - '8000:8000'