version: '3.9'
services:
  server:
    build: .
    # ports:
    #   - 8000:8000
  nginx:
    image: nginx:latest
    depends_on:
      - server
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - '8000:8000'
